---
title: "Climate_Diference"
author: "Santiago Esteban"
date: "May 1, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Creating dataset with the diference in climate factors comapring the index week to four weeks before.

```{r}
#Loading climate data
library(dplyr)
library(readr)
library(lubridate)
library(tidyr)
library(stringr)
library(ggplot2)
library(readxl)
library(ggmap)
library(RNetCDF)
library(xlsx)
library(ggmap)
library(sp)
library(gganimate)
library(ggrepel)
library(gridExtra)
library(RColorBrewer)
library(knitr)

#Loading datasets created in previous step and adding information on the peaks of onset
guinea_weekly_cases_climate <- read.csv('guinea_weekly_cases_climate.csv')
guinea_weekly_cases_climate$Weeks <- dmy(guinea_weekly_cases_climate$Weeks)
guinea_weekly_cases_climate <- group_by(guinea_weekly_cases_climate, Location) %>% mutate(Peak=ifelse(Total_cases>0 & Total_cases==max(Total_cases),1,0), Cum_peak=cumsum(Peak)) %>% ungroup


SL_weekly_cases_climate <- read.csv('SL_weekly_cases_climate.csv')
SL_weekly_cases_climate$Weeks <- ymd(SL_weekly_cases_climate$Weeks)
SL_weekly_cases_climate <- group_by(SL_weekly_cases_climate, Location) %>% mutate(Peak=ifelse(Total_cases>0 & Total_cases==max(Total_cases),1,0), Cum_peak=cumsum(Peak)) %>% ungroup

Liberia_weekly_cases_climate <- read.csv('Liberia_weekly_cases_climate.csv')
Liberia_weekly_cases_climate$Weeks <- dmy(Liberia_weekly_cases_climate$Weeks)
Liberia_weekly_cases_climate <- group_by(Liberia_weekly_cases_climate, Location) %>% mutate(Peak=ifelse(Total_cases>0 & Total_cases==max(Total_cases),1,0), Cum_peak=cumsum(Peak)) %>% ungroup

#Creating diferences in cliamte factors for the three countries
#Guinea
tmp.dif <- list()
for(i in 60:152){
            tmp.dif[[i]] <- guinea_weekly_cases_climate$tmp[guinea_weekly_cases_climate$count_week==i]-guinea_weekly_cases_climate$tmp[guinea_weekly_cases_climate$count_week==i-4]
}

tmn.dif <- list()
for(i in 60:152){
            tmn.dif[[i]] <- guinea_weekly_cases_climate$tmn[guinea_weekly_cases_climate$count_week==i]-guinea_weekly_cases_climate$tmn[guinea_weekly_cases_climate$count_week==i-4]
}

tmx.dif <- list()
for(i in 60:152){
            tmx.dif[[i]] <- guinea_weekly_cases_climate$tmx[guinea_weekly_cases_climate$count_week==i]-guinea_weekly_cases_climate$tmx[guinea_weekly_cases_climate$count_week==i-4]
}

pre.dif <- list()
for(i in 60:152){
            pre.dif[[i]] <- guinea_weekly_cases_climate$pre[guinea_weekly_cases_climate$count_week==i]-guinea_weekly_cases_climate$pre[guinea_weekly_cases_climate$count_week==i-4]
}

vap.dif <- list()
for(i in 60:152){
            vap.dif[[i]] <- guinea_weekly_cases_climate$vap[guinea_weekly_cases_climate$count_week==i]-guinea_weekly_cases_climate$vap[guinea_weekly_cases_climate$count_week==i-4]
}

guinea_climate_dif <- as.data.frame(cbind(Location=as.character(unique(guinea_weekly_cases_climate$Location)), count_week=sort(rep(60:152, 34)), tmp_dif=unlist(tmp.dif), tmx_dif=unlist(tmx.dif), tmn_dif=unlist(tmn.dif), pre_dif=unlist(pre.dif), vap_dif=unlist(vap.dif)))
guinea_climate_dif$count_week <- as.numeric(as.character(guinea_climate_dif$count_week))

#Joining with case count data
guinea_climate_dif <- left_join(guinea_climate_dif, select(guinea_weekly_cases_climate, Location, count_week, Total_cases, Weeks), by=c('Location', 'count_week'))

save(guinea_climate_dif, file='guinea_climate_dif.Rdata')

#Sierra Leone
tmp.dif <- list()
for(i in 60:152){
            tmp.dif[[i]] <- SL_weekly_cases_climate$tmp[SL_weekly_cases_climate$count_week==i]-SL_weekly_cases_climate$tmp[SL_weekly_cases_climate$count_week==i-4]
}

tmn.dif <- list()
for(i in 60:152){
            tmn.dif[[i]] <- SL_weekly_cases_climate$tmn[SL_weekly_cases_climate$count_week==i]-SL_weekly_cases_climate$tmn[SL_weekly_cases_climate$count_week==i-4]
}

tmx.dif <- list()
for(i in 60:152){
            tmx.dif[[i]] <- SL_weekly_cases_climate$tmx[SL_weekly_cases_climate$count_week==i]-SL_weekly_cases_climate$tmx[SL_weekly_cases_climate$count_week==i-4]
}

pre.dif <- list()
for(i in 60:152){
            pre.dif[[i]] <- SL_weekly_cases_climate$pre[SL_weekly_cases_climate$count_week==i]-SL_weekly_cases_climate$pre[SL_weekly_cases_climate$count_week==i-4]
}

vap.dif <- list()
for(i in 60:152){
            vap.dif[[i]] <- SL_weekly_cases_climate$vap[SL_weekly_cases_climate$count_week==i]-SL_weekly_cases_climate$vap[SL_weekly_cases_climate$count_week==i-4]
}

SL_climate_dif <- as.data.frame(cbind(Location=as.character(unique(SL_weekly_cases_climate$Location)), count_week=sort(rep(60:152, 14)), tmp_dif=unlist(tmp.dif), tmx_dif=unlist(tmx.dif), tmn_dif=unlist(tmn.dif), pre_dif=unlist(pre.dif), vap_dif=unlist(vap.dif)))
SL_climate_dif$count_week <- as.numeric(as.character(SL_climate_dif$count_week))

#Joining with case count data
SL_climate_dif <- left_join(SL_climate_dif, select(SL_weekly_cases_climate, Location, count_week, Total_cases, Weeks), by=c('Location', 'count_week'))

save(SL_climate_dif, file='SL_climate_dif.Rdata')

#Sierra Leone
tmp.dif <- list()
for(i in 60:152){
            tmp.dif[[i]] <- Liberia_weekly_cases_climate$tmp[Liberia_weekly_cases_climate$count_week==i]-Liberia_weekly_cases_climate$tmp[Liberia_weekly_cases_climate$count_week==i-4]
}

tmn.dif <- list()
for(i in 60:152){
            tmn.dif[[i]] <- Liberia_weekly_cases_climate$tmn[Liberia_weekly_cases_climate$count_week==i]-Liberia_weekly_cases_climate$tmn[Liberia_weekly_cases_climate$count_week==i-4]
}

tmx.dif <- list()
for(i in 60:152){
            tmx.dif[[i]] <- Liberia_weekly_cases_climate$tmx[Liberia_weekly_cases_climate$count_week==i]-Liberia_weekly_cases_climate$tmx[Liberia_weekly_cases_climate$count_week==i-4]
}

pre.dif <- list()
for(i in 60:152){
            pre.dif[[i]] <- Liberia_weekly_cases_climate$pre[Liberia_weekly_cases_climate$count_week==i]-Liberia_weekly_cases_climate$pre[Liberia_weekly_cases_climate$count_week==i-4]
}

vap.dif <- list()
for(i in 60:152){
            vap.dif[[i]] <- Liberia_weekly_cases_climate$vap[Liberia_weekly_cases_climate$count_week==i]-Liberia_weekly_cases_climate$vap[Liberia_weekly_cases_climate$count_week==i-4]
}

Liberia_climate_dif <- as.data.frame(cbind(Location=as.character(unique(Liberia_weekly_cases_climate$Location)), count_week=sort(rep(60:152, 15)), tmp_dif=unlist(tmp.dif), tmx_dif=unlist(tmx.dif), tmn_dif=unlist(tmn.dif), pre_dif=unlist(pre.dif), vap_dif=unlist(vap.dif)))
Liberia_climate_dif$count_week <- as.numeric(as.character(Liberia_climate_dif$count_week))

#Joining with case count data
Liberia_climate_dif <- left_join(Liberia_climate_dif, select(Liberia_weekly_cases_climate, Location, count_week, Total_cases, Weeks), by=c('Location', 'count_week'))

save(Liberia_climate_dif, file='Liberia_climate_dif.Rdata')

```

